os: osx
addons:
  homebrew:
    - dependency-check
language: node_js
node_js:
  - "10"
before_script:
  - dependency-check --format JSON --format HTML --scan . --enableExperimental --disableOssIndex --prettyPrint --failOnCVSS 1
script:
  - npm run build
